<?php


$fathersname = $this->helper('TrainingJaymin\CustomerAttribute\Helper\Data')
    ->getConfig('helloworld/general/fathersname');

$mothersname = $this->helper('TrainingJaymin\CustomerAttribute\Helper\Data')
    ->getConfig('helloworld/general/mothersname');




?>
<?php
if($mothersname == 1)
{
    ?>
    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
        <p>
        <div class="field regulation">
            <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Mothers Name') ?></span></label>
            <div class="control">
                <input type="text" name="mother_name" id="mother_name" title="<?php /* @escapeNotVerified */ echo __('Mothers Name1') ?>"
                       class="input-text" data-validate="{required:false}">
            </div>
        </div>
        </p>
    </fieldset>
    <?php
}
if($fathersname == 1)
{
    ?>
    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
        <p>
        <div class="field regulation">
            <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                    echo __('Fathers Name') ?></span></label>
            <div class="control">
                <input type="text" name="father_name" id="father_name" title="<?php /* @escapeNotVerified */ echo __('Fathers Name') ?>"
                       class="input-text" data-validate="{required:false}">
            </div>
        </div>
        </p>
    </fieldset>
    <?php
}
?>

