<?php

/** @var \TrainingJaymin\CountdownTimer\Block\Hello $block */


//$hello = $block->getHelloWorld();
$attributeCode = 'deal_available';
$entityType = 'catalog_product';

//echo '<pre>';
//$attrTest = $block->getHelloWorld();
//print_r($block->getDealAvailable());
//print_r($block->getDealStatus());
//$status = $block->getDealStatus();




?>

<div data-mage-init='{"hello": {"message": "<?php $block->getDealStatus(); ?>"}}' id="timerdiv" style="font-weight: bold; color:red;">
</div>

